@Library('aldo-jenkins-shared') _

standardJavaPipeline(
  repository: 'https://github.com/aldo2510/ec-maven-users-api.git',
  branch: 'main',
  image: 'maven:3.9.3-eclipse-temurin-17',
  goals: 'clean package'
)
